### ISSUE TITLE
Deprecated constants in use for door close and open operations

### ISSUE THREAD

**Issue by eth0up** [corporategoth/ha-powerpetdoor#12]
### Describe the bug
Home Assistant system logs (Core) indicate that the constants currently used by this integration are deprecated.

### Steps To Reproduce
1. Interact with Power Pet Door using Home Assistant 
2. Check system logs (Core) to see the deprecation warning message:
```
• SUPPORT_CLOSE was used from powerpetdoor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.CLOSE instead, please create a bug report at https://github.com/corporategoth/ha-powerpetdoor/issues
• SUPPORT_OPEN was used from powerpetdoor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN instead, please create a bug report at https://github.com/corporategoth/ha-powerpetdoor/issues
```

### Expected behavior
Use `CoverEntityFeature.CLOSE` and `CoverEntityFeature.OPEN` instead of `SUPPORT_CLOSE` and `SUPPORT_OPEN` since they will be deprecated in Home Assistant 2025.1.

### Environment
 - Home Assistant Version: 2024.1.3
 - Power Pet Door Integration Version: 0.4.3
 - Power Pet Door Model: PX2-WIFI
 - Power Pet Door Firmware Version: 1.7.16
 - Power Pet Door Hardware Version: 1 rev 1

**Comment by corporategoth** [comment]
Thanks - fixed here - https://github.com/corporategoth/ha-powerpetdoor/commit/aaf4efdf986f158a904bf4ac2f0e5578701aa833
Given there is a whole year until it's removed, this will go out with whatever the next release of the power pet door is.  It's not urgent :)

Thanks for the report.

**Comment by scottleestrange** [comment]
It's urgent now.
