### ISSUE TITLE
Unable to find repositories

### ISSUE THREAD

**Issue by donaldrke** [corporategoth/ha-powerpetdoor#5]
First I am  pretty new. But after many attempts unable to find the repositories. Hacs is installed

**Comment by corporategoth** [comment]
Find what repositories?

**Comment by donaldrke** [comment]
When I follow the directions,  and put in custom repositories. It just spins and nothing happens. No other screen.

**Comment by donaldrke** [comment]
Again I maybe missing something.  But trying to learn also.

**Comment by donaldrke** [comment]
yeah I got it. Now I just need to configure it. 
The searching for power pet door did not find anything

But when I put https://github.com/corporategoth/ha-powerpetdoor
that worked perfectly

Sorry for confusing, just learning about HA and watch alot of videos but nothing like talking to someone or seeing something show up.

What part of VA you from, near Roanoke here

Again Thanks for the Help
