### ISSUE TITLE
Door showing offline

### ISSUE THREAD

**Issue by laxfiend77** [corporategoth/ha-powerpetdoor#6]
Pet door went offline after recent homeassistant updates

**Comment by corporategoth** [comment]
This is nowhere NEAR enough information for me to go on.

Can you turn on debug logging, in your configuration.yaml, add:
```
logger:
  logs:
      custom_components.powerpetdoor: debug
```

Then re-start your Home Assistant.

Attach the logs pertaining to `custom_components.powerpetdoor`

**Comment by corporategoth** [comment]
Closing due to 2 months of inactivity.
